import { useState, useEffect } from 'react';
import {
    Users, UserX, Ban, Search, Crown,
    UserCheck, AlertTriangle, RefreshCw,
    Heart, Utensils, Zap, Skull, Box, FileCode,
    Activity, ArrowLeft, Sword, Map, Eye
} from 'lucide-react';
import { toast } from 'sonner';
import { invoke } from '@tauri-apps/api/core';
import { cn } from '../../lib/utils';
import { ServerType } from '../../stores/appStore';

interface PlayerManagerProps {
    sendCommand: (e?: React.FormEvent, cmdStr?: string) => Promise<void>;
    isRunning: boolean;
    activePlayers: string[];
    serverType: ServerType;
    serverName: string;
    serverPath: string;
}

type PlayerTab = 'online' | 'ops' | 'whitelist' | 'banned' | 'banned-ips';

interface PlayerEntry {
    name: string;
    uuid?: string;
    addedAt?: string | null;
}

interface UserCacheEntry {
    name: string;
    uuid: string;
    expiresOn: string;
}

export function PlayerManager({
    sendCommand,
    isRunning,
    activePlayers,
    serverType,
    serverName,
    serverPath
}: PlayerManagerProps) {
    const [activeTab, setActiveTab] = useState<PlayerTab>('online');
    const [selectedPlayer, setSelectedPlayer] = useState<string | null>(null);
    const [newPlayer, setNewPlayer] = useState('');
    const [searchQuery, setSearchQuery] = useState('');
    const [showTeleportModal, setShowTeleportModal] = useState(false);
    const [tpCoords, setTpCoords] = useState("");

    // Data Lists
    const [ops, setOps] = useState<PlayerEntry[]>([]);
    const [whitelist, setWhitelist] = useState<PlayerEntry[]>([]);
    const [bannedPlayers, setBannedPlayers] = useState<PlayerEntry[]>([]);
    const [bannedIps, setBannedIps] = useState<string[]>([]);
    const [playerHistory, setPlayerHistory] = useState<string[]>([]);
    const [userCache, setUserCache] = useState<UserCacheEntry[]>([]);
    const [loading, setLoading] = useState(false);

    const isBedrock = serverType === 'bedrock';

    useEffect(() => {
        loadPlayerData();
    }, [serverPath]);

    // Track and persist player history
    useEffect(() => {
        // Load initial history
        if (!loading) {
            invoke<string>('read_server_file', { path: `${serverPath}\\player-history.json` })
                .then(content => {
                    try {
                        const history = JSON.parse(content);
                        if (Array.isArray(history)) setPlayerHistory(history);
                    } catch (e) {
                        // File might not exist yet, that's fine
                    }
                })
                .catch(() => { });
        }
    }, [serverPath]);

    // Update history when active players change
    useEffect(() => {
        if (activePlayers.length > 0) {
            setPlayerHistory(prev => {
                const uniqueSet = new Set([...prev, ...activePlayers]);
                const updated = Array.from(uniqueSet);

                // Only write if changed
                if (updated.length !== prev.length) {
                    invoke('write_server_file', {
                        path: `${serverPath}\\player-history.json`,
                        content: JSON.stringify(updated)
                    }).catch(err => console.error("Failed to save history:", err));
                }
                return updated;
            });
        }
    }, [activePlayers, serverPath]);

    async function loadPlayerData() {
        setLoading(true);
        try {
            const loadFile = async (file: string) => {
                try {
                    const c = await invoke<string>('read_server_file', { path: `${serverPath}\\${file}` });
                    const data = JSON.parse(c);
                    return Array.isArray(data) ? data : [];
                } catch { return []; }
            };

            // Bedrock uses different files
            const opFile = isBedrock ? 'permissions.json' : 'ops.json';
            const wlFile = isBedrock ? 'allowlist.json' : 'whitelist.json';

            const [opsData, wlData, banData, ipData, cacheData] = await Promise.all([
                loadFile(opFile),
                loadFile(wlFile),
                loadFile('banned-players.json'),
                loadFile('banned-ips.json'),
                loadFile('usercache.json')
            ]);

            // Normalize Bedrock permissions.json (often just xuid/permission)
            if (isBedrock) {
                // Bedrock permissions usually don't have 'name' directly if generated by server, 
                // but we can try to map if we have cache, or just show xuid/permission.
                // Assuming standard BDS format: [ { "permission": "operator", "xuid": "..." } ]
                // Allowlist: [ { "ignoresPlayerLimit": false, "name": "...", "xuid": "..." } ]

                setOps(opsData.filter((o: any) => o.permission === 'operator' || o.permission === 'admin').map((o: any) => ({
                    name: o.name || `XUID: ${o.xuid}`, // Fallback if name missing
                    uuid: o.xuid,
                    addedAt: null
                })));

                setWhitelist(wlData.map((w: any) => ({
                    name: w.name,
                    uuid: w.xuid,
                    addedAt: null
                })));
            } else {
                // Java Format
                setOps(opsData.map((o: any) => ({ name: o.name, uuid: o.uuid, addedAt: null })));
                setWhitelist(wlData.map((w: any) => ({ name: w.name, uuid: w.uuid, addedAt: null })));
            }

            setBannedPlayers(banData.map((b: any) => ({
                name: b.name,
                uuid: b.uuid || b.xuid,
                reason: b.reason,
                source: b.source,
                addedAt: b.created
            })));

            setBannedIps(ipData.map((i: any) => i.ip));
            setUserCache(cacheData);

        } catch (err) {
            console.error('Failed to load player data:', err);
        } finally {
            setLoading(false);
        }
    }

    const cmd = async (command: string) => {
        if (!isRunning) {
            toast.error('Server is not running');
            return;
        }
        await sendCommand(undefined, command);
        toast.success(`Executed: /${command}`);
        setTimeout(loadPlayerData, 1000);
    };

    const handleAddPlayer = async () => {
        if (!newPlayer.trim()) return;
        switch (activeTab) {
            case 'ops': await cmd(`op ${newPlayer}`); break;
            case 'whitelist': await cmd(`whitelist add ${newPlayer}`); break;
            case 'banned': await cmd(`ban ${newPlayer}`); break;
        }
        setNewPlayer('');
    };



    const getPlayerUuid = (name: string) => {
        const cached = userCache.find(u => u.name.toLowerCase() === name.toLowerCase());
        if (cached) return cached.uuid;
        const op = ops.find(o => o.name.toLowerCase() === name.toLowerCase());
        if (op) return op.uuid;
        return null; // UUID unknown
    };

    const handleDeleteData = async (type: 'playerdata' | 'stats' | 'advancements') => {
        if (!selectedPlayer) return;
        const uuid = getPlayerUuid(selectedPlayer);
        if (!uuid) {
            toast.error(`UUID not found for ${selectedPlayer}. Cannot delete files.`);
            return;
        }

        const confirm = await window.confirm(`Delete ${type} for ${selectedPlayer}? This cannot be undone.`);
        if (!confirm) return;

        let filePath = '';
        if (type === 'playerdata') filePath = `world\\playerdata\\${uuid}.dat`;
        if (type === 'stats') filePath = `world\\stats\\${uuid}.json`;
        if (type === 'advancements') filePath = `world\\advancements\\${uuid}.json`;

        try {
            await invoke('delete_file', { path: `${serverPath}\\${filePath}` });
            toast.success(`Deleted ${type} for ${selectedPlayer}`);
        } catch (e) {
            toast.error(`Failed to delete file: ${e}`);
        }
    };

    const renderDetailedView = () => {
        if (!selectedPlayer) return null;
        const isOnline = activePlayers.includes(selectedPlayer);
        const isOp = ops.some(o => o.name === selectedPlayer);
        const isWhitelisted = whitelist.some(w => w.name === selectedPlayer);
        const isBanned = bannedPlayers.some(b => b.name === selectedPlayer);
        const uuid = getPlayerUuid(selectedPlayer);

        return (
            <div className="flex flex-col h-full bg-[#0d1117] animate-in slide-in-from-right-10 duration-200">
                {/* Header */}
                <div className="p-4 border-b border-border/50 bg-[#161b22] flex items-center justify-between">
                    <button onClick={() => setSelectedPlayer(null)} className="flex items-center gap-2 text-text-muted hover:text-white transition-colors">
                        <ArrowLeft className="w-5 h-5" />
                        <span className="font-medium">Back to List</span>
                    </button>
                    <div className="flex items-center gap-2">
                        {isOnline ? (
                            <span className="bg-green-500/10 text-green-400 px-3 py-1 rounded-full text-xs font-bold border border-green-500/20 flex items-center gap-1">
                                <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
                                ONLINE
                            </span>
                        ) : (
                            <span className="bg-red-500/10 text-red-400 px-3 py-1 rounded-full text-xs font-bold border border-red-500/20">
                                OFFLINE
                            </span>
                        )}
                    </div>
                </div>

                <div className="flex-1 overflow-y-auto p-6 space-y-6">
                    {/* Profile Header */}
                    <div className="flex items-start gap-6">
                        <div className="w-24 h-24 rounded-2xl bg-surface-hover flex items-center justify-center text-4xl font-bold text-text-muted border-2 border-border shadow-2xl relative overflow-hidden group">
                            {/* Avatar Placeholder */}
                            <img
                                src={`https://minotar.net/avatar/${selectedPlayer}/100.png`}
                                alt={selectedPlayer}
                                className="w-full h-full object-cover"
                                onError={(e) => { (e.target as HTMLImageElement).src = ''; }}
                            />
                            <div className="absolute inset-0 bg-black/50 hidden group-hover:flex items-center justify-center text-white text-xs font-medium">
                                {isBedrock ? 'Bedrock' : 'Java'}
                            </div>
                        </div>
                        <div className="flex-1">
                            <h1 className="text-3xl font-bold text-white mb-2">{selectedPlayer}</h1>
                            <div className="flex flex-wrap gap-2 mb-2">
                                {isOp && <span className="px-2 py-0.5 rounded bg-yellow-500/20 text-yellow-400 text-xs font-bold border border-yellow-500/30">OPERATOR</span>}
                                {isWhitelisted && <span className="px-2 py-0.5 rounded bg-blue-500/20 text-blue-400 text-xs font-bold border border-blue-500/30">WHITELISTED</span>}
                                {isBanned && <span className="px-2 py-0.5 rounded bg-red-500/20 text-red-400 text-xs font-bold border border-red-500/30">BANNED</span>}
                            </div>
                            <p className="text-xs text-text-muted font-mono">{uuid || 'UUID Not Found (Offline/Unknown)'}</p>
                        </div>
                    </div>

                    {/* Quick Actions */}
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                        <button onClick={() => cmd(isOp ? `deop ${selectedPlayer}` : `op ${selectedPlayer}`)} className={cn("p-3 rounded-xl border flex flex-col items-center gap-2 transition-all", isOp ? "bg-yellow-500/10 border-yellow-500/30 text-yellow-400 hover:bg-yellow-500/20" : "bg-surface border-border hover:bg-surface-hover")}>
                            <Crown className="w-5 h-5" />
                            <span className="text-xs font-bold">{isOp ? 'Remove OP' : 'Make OP'}</span>
                        </button>
                        <button onClick={() => cmd(isWhitelisted ? `whitelist remove ${selectedPlayer}` : `whitelist add ${selectedPlayer}`)} className={cn("p-3 rounded-xl border flex flex-col items-center gap-2 transition-all", isWhitelisted ? "bg-blue-500/10 border-blue-500/30 text-blue-400 hover:bg-blue-500/20" : "bg-surface border-border hover:bg-surface-hover")}>
                            <UserCheck className="w-5 h-5" />
                            <span className="text-xs font-bold">{isWhitelisted ? 'Un-Whitelist' : 'Whitelist'}</span>
                        </button>
                        <button onClick={() => cmd(isBanned ? `pardon ${selectedPlayer}` : `ban ${selectedPlayer}`)} className={cn("p-3 rounded-xl border flex flex-col items-center gap-2 transition-all", isBanned ? "bg-green-500/10 border-green-500/30 text-green-400 hover:bg-green-500/20" : "bg-red-500/10 border-red-500/30 text-red-400 hover:bg-red-500/20")}>
                            {isBanned ? <UserCheck className="w-5 h-5" /> : <Ban className="w-5 h-5" />}
                            <span className="text-xs font-bold">{isBanned ? 'Unban' : 'Ban Player'}</span>
                        </button>
                    </div>

                    {/* Gamemode Selection */}
                    <div className="space-y-4">
                        <h3 className="text-sm font-bold text-text-muted uppercase tracking-wider">Gamemode</h3>
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                            <button onClick={() => cmd(`gamemode survival ${selectedPlayer}`)} className="p-3 rounded-xl bg-surface border border-border hover:border-red-500/50 hover:bg-red-500/5 hover:text-red-400 transition-all flex flex-col items-center gap-2 group">
                                <Sword className="w-5 h-5 text-text-secondary group-hover:text-red-400 transition-colors" />
                                <span className="text-xs font-bold">Survival</span>
                            </button>
                            <button onClick={() => cmd(`gamemode creative ${selectedPlayer}`)} className="p-3 rounded-xl bg-surface border border-border hover:border-blue-500/50 hover:bg-blue-500/5 hover:text-blue-400 transition-all flex flex-col items-center gap-2 group">
                                <Box className="w-5 h-5 text-text-secondary group-hover:text-blue-400 transition-colors" />
                                <span className="text-xs font-bold">Creative</span>
                            </button>
                            <button onClick={() => cmd(`gamemode adventure ${selectedPlayer}`)} className="p-3 rounded-xl bg-surface border border-border hover:border-yellow-500/50 hover:bg-yellow-500/5 hover:text-yellow-400 transition-all flex flex-col items-center gap-2 group">
                                <Map className="w-5 h-5 text-text-secondary group-hover:text-yellow-400 transition-colors" />
                                <span className="text-xs font-bold">Adventure</span>
                            </button>
                            <button onClick={() => cmd(`gamemode spectator ${selectedPlayer}`)} className="p-3 rounded-xl bg-surface border border-border hover:border-purple-500/50 hover:bg-purple-500/5 hover:text-purple-400 transition-all flex flex-col items-center gap-2 group">
                                <Eye className="w-5 h-5 text-text-secondary group-hover:text-purple-400 transition-colors" />
                                <span className="text-xs font-bold">Spectator</span>
                            </button>
                        </div>
                    </div>

                    {/* Fun & Management */}
                    <div className="space-y-4">
                        <h3 className="text-sm font-bold text-text-muted uppercase tracking-wider">Gameplay Actions</h3>
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                            <button onClick={() => cmd(isBedrock ? `effect ${selectedPlayer} instant_health 1 255` : `effect give ${selectedPlayer} minecraft:instant_health 1 255`)} className="group p-3 rounded-xl bg-surface border border-border hover:border-pink-500/50 hover:bg-pink-500/5 transition-all flex flex-col items-center gap-2">
                                <Heart className="w-5 h-5 text-pink-500 group-hover:scale-110 transition-transform" />
                                <span className="text-xs font-bold text-text">Heal</span>
                            </button>
                            <button onClick={() => cmd(isBedrock ? `effect ${selectedPlayer} saturation 1 255` : `effect give ${selectedPlayer} minecraft:saturation 1 255`)} className="group p-3 rounded-xl bg-surface border border-border hover:border-orange-500/50 hover:bg-orange-500/5 transition-all flex flex-col items-center gap-2">
                                <Utensils className="w-5 h-5 text-orange-500 group-hover:scale-110 transition-transform" />
                                <span className="text-xs font-bold text-text">Feed</span>
                            </button>
                            <button onClick={() => cmd(isBedrock ? `effect ${selectedPlayer} hunger 30 255` : `effect give ${selectedPlayer} minecraft:hunger 30 255`)} className="group p-3 rounded-xl bg-surface border border-border hover:border-green-800/50 hover:bg-green-900/10 transition-all flex flex-col items-center gap-2">
                                <Skull className="w-5 h-5 text-green-700 group-hover:scale-110 transition-transform" />
                                <span className="text-xs font-bold text-text">Starve</span>
                            </button>
                            <button onClick={() => cmd(`execute at ${selectedPlayer} run summon lightning_bolt`)} className="group p-3 rounded-xl bg-surface border border-border hover:border-yellow-400/50 hover:bg-yellow-400/5 transition-all flex flex-col items-center gap-2">
                                <Zap className="w-5 h-5 text-yellow-400 group-hover:scale-110 transition-transform" />
                                <span className="text-xs font-bold text-text">Smite</span>
                            </button>
                        </div>
                    </div>

                    {/* Teleport */}
                    <div className="space-y-4">
                        <h3 className="text-sm font-bold text-text-muted uppercase tracking-wider">Teleportation</h3>
                        <div className="flex gap-2">
                            <button onClick={() => cmd(`tp ${selectedPlayer} ~ ~ ~`)} className="flex-1 px-4 py-2 bg-primary/10 text-primary border border-primary/20 rounded-lg text-sm font-bold hover:bg-primary/20">
                                TP Here
                            </button>
                            <button onClick={() => cmd(`tp ${selectedPlayer} 0 100 0`)} className="flex-1 px-4 py-2 bg-surface text-text border border-border rounded-lg text-sm font-bold hover:bg-surface-hover">
                                TP to Spawn (0,0)
                            </button>
                            <button onClick={() => cmd(`kill ${selectedPlayer}`)} className="px-4 py-2 bg-red-500/10 text-red-500 border border-red-500/20 rounded-lg text-sm font-bold hover:bg-red-500/20">
                                Kill
                            </button>
                        </div>
                    </div>

                    {/* Advanced / File Data */}
                    {!isBedrock && (
                        <div className="space-y-4 pt-4 border-t border-border/30">
                            <h3 className="text-sm font-bold text-red-400 uppercase tracking-wider flex items-center gap-2">
                                <AlertTriangle className="w-4 h-4" /> Danger Zone
                            </h3>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                                <button onClick={() => handleDeleteData('playerdata')} className="p-3 rounded-xl bg-[#1f1212] border border-red-500/20 hover:border-red-500/50 flex items-center gap-3 transition-colors text-left">
                                    <div className="p-2 rounded-lg bg-red-500/10 text-red-500"><Box className="w-4 h-4" /></div>
                                    <div>
                                        <div className="text-sm font-bold text-red-200">Inventory</div>
                                        <div className="text-[10px] text-red-400/60">Delete .dat file</div>
                                    </div>
                                </button>
                                <button onClick={() => handleDeleteData('stats')} className="p-3 rounded-xl bg-[#1f1212] border border-red-500/20 hover:border-red-500/50 flex items-center gap-3 transition-colors text-left">
                                    <div className="p-2 rounded-lg bg-red-500/10 text-red-500"><Activity className="w-4 h-4" /></div>
                                    <div>
                                        <div className="text-sm font-bold text-red-200">Statistics</div>
                                        <div className="text-[10px] text-red-400/60">Reset stats.json</div>
                                    </div>
                                </button>
                                <button onClick={() => handleDeleteData('advancements')} className="p-3 rounded-xl bg-[#1f1212] border border-red-500/20 hover:border-red-500/50 flex items-center gap-3 transition-colors text-left">
                                    <div className="p-2 rounded-lg bg-red-500/10 text-red-500"><FileCode className="w-4 h-4" /></div>
                                    <div>
                                        <div className="text-sm font-bold text-red-200">Advancements</div>
                                        <div className="text-[10px] text-red-400/60">Reset advancements</div>
                                    </div>
                                </button>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        );
    };



    const getFilteredList = () => {
        let list: any[] = [];
        switch (activeTab) {
            case 'online': list = activePlayers.map(name => ({ name })); break;
            case 'ops': list = ops; break;
            case 'whitelist': list = whitelist; break;
            case 'banned': list = bannedPlayers; break;
            case 'banned-ips': list = bannedIps.map(ip => ({ name: ip, isIp: true })); break;
        }
        if (!searchQuery) return list;
        return list.filter(item => item.name.toLowerCase().includes(searchQuery.toLowerCase()));
    };

    const displayedList = getFilteredList();

    if (selectedPlayer) {
        return renderDetailedView();
    }

    const tabs = [
        { id: 'online' as PlayerTab, label: 'Online', icon: Users, count: activePlayers.length, color: 'text-green-400', bg: 'bg-green-500/10', border: 'border-green-500/20' },
        { id: 'ops' as PlayerTab, label: 'Operators', icon: Crown, count: ops.length, color: 'text-yellow-400', bg: 'bg-yellow-500/10', border: 'border-yellow-500/20' },
        { id: 'whitelist' as PlayerTab, label: 'Whitelist', icon: UserCheck, count: whitelist.length, color: 'text-blue-400', bg: 'bg-blue-500/10', border: 'border-blue-500/20' },
        { id: 'banned' as PlayerTab, label: 'Banned', icon: UserX, count: bannedPlayers.length, color: 'text-red-400', bg: 'bg-red-500/10', border: 'border-red-500/20' },
        { id: 'banned-ips' as PlayerTab, label: 'IP Bans', icon: Ban, count: bannedIps.length, color: 'text-purple-400', bg: 'bg-purple-500/10', border: 'border-purple-500/20' },
    ];



    const handleTeleport = async () => {
        if (!selectedPlayer || !tpCoords.trim()) return;
        await cmd(`tp ${selectedPlayer} ${tpCoords}`);
        setShowTeleportModal(false);
        setTpCoords("");
    };

    return (
        <div className="flex flex-col h-full bg-[#0d1117]">
            {/* Teleport Modal */}
            {showTeleportModal && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-in fade-in zoom-in-95">
                    <div className="bg-[#161b22] border border-border rounded-xl w-full max-w-sm p-5 shadow-2xl relative" onClick={e => e.stopPropagation()}>
                        <button onClick={() => setShowTeleportModal(false)} className="absolute top-4 right-4 text-text-muted hover:text-white"><UserX className="w-4 h-4 rotate-45" /></button>
                        <h3 className="font-bold text-white mb-4 flex items-center gap-2"><Map className="w-5 h-5 text-primary" /> Teleport {selectedPlayer}</h3>

                        <div className="space-y-5">
                            {/* Option 1: To Player */}
                            <div>
                                <label className="text-xs font-bold text-text-muted mb-2 block uppercase tracking-wider">To Another Player</label>
                                <div className="grid grid-cols-2 gap-2 max-h-32 overflow-y-auto custom-scrollbar">
                                    {activePlayers.filter(p => p !== selectedPlayer).length === 0 ? (
                                        <p className="text-xs text-text-muted col-span-2 italic text-center py-2">No other players online</p>
                                    ) : (
                                        activePlayers.filter(p => p !== selectedPlayer).map(p => (
                                            <button
                                                key={p}
                                                onClick={() => { cmd(`tp ${selectedPlayer} ${p}`); setShowTeleportModal(false); }}
                                                className="flex items-center gap-2 p-2 rounded-lg bg-surface border border-border hover:border-primary/50 hover:bg-primary/10 transition-all text-left"
                                            >
                                                <img src={`https://minotar.net/avatar/${p}/24.png`} className="w-6 h-6 rounded-md" />
                                                <span className="text-xs font-bold text-white truncate">{p}</span>
                                            </button>
                                        ))
                                    )}
                                </div>
                            </div>

                            <div className="relative">
                                <div className="absolute inset-0 flex items-center"><div className="w-full border-t border-border/50"></div></div>
                                <div className="relative flex justify-center text-xs uppercase"><span className="bg-[#161b22] px-2 text-text-muted">OR Coordinates</span></div>
                            </div>

                            {/* Option 2: Coordinates */}
                            <div className="flex gap-2">
                                <input
                                    value={tpCoords}
                                    onChange={(e) => setTpCoords(e.target.value)}
                                    placeholder="x y z"
                                    className="flex-1 bg-black/30 border border-border rounded-lg px-3 py-2.5 text-white outline-none focus:border-primary font-mono text-sm"
                                    onKeyDown={(e) => e.key === 'Enter' && handleTeleport()}
                                />
                                <button
                                    onClick={handleTeleport}
                                    disabled={!tpCoords.trim()}
                                    className="px-4 bg-primary text-black font-bold rounded-lg disabled:opacity-50 hover:bg-primary/90 transition-colors"
                                >
                                    Go
                                </button>
                            </div>
                            <p className="text-[10px] text-text-muted text-center">Use <code>~</code> for relative. Example: <code>~ 100 ~</code></p>
                        </div>
                    </div>
                </div>
            )}

            {/* Header */}
            <div className="p-4 border-b border-border/50 bg-[#161b22]">
                <div className="flex items-center justify-between mb-4">
                    <div>
                        <h2 className="text-lg font-bold text-white flex items-center gap-2">
                            {serverName}
                            <span className={cn("text-xs px-2 py-0.5 rounded font-bold border", isBedrock ? "bg-green-500/10 text-green-400 border-green-500/20" : "bg-orange-500/10 text-orange-400 border-orange-500/20")}>
                                {isBedrock ? 'BEDROCK' : 'JAVA'}
                            </span>
                        </h2>
                    </div>
                    <div className="flex items-center gap-2">
                        <button onClick={loadPlayerData} className="p-2 rounded-lg hover:bg-white/10 text-text-muted hover:text-white transition-colors">
                            <RefreshCw className={cn("w-4 h-4", loading && "animate-spin")} />
                        </button>
                    </div>
                </div>

                <div className="flex gap-1 overflow-x-auto pb-1 no-scrollbar">
                    {tabs.map(tab => (
                        <button
                            key={tab.id}
                            onClick={() => { setActiveTab(tab.id); setSearchQuery(''); }}
                            className={cn(
                                "flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium whitespace-nowrap transition-all border",
                                activeTab === tab.id
                                    ? `${tab.bg} ${tab.color} ${tab.border}`
                                    : "border-transparent text-text-muted hover:text-white hover:bg-white/5"
                            )}
                        >
                            <tab.icon className="w-4 h-4" />
                            {tab.label}
                            {tab.count > 0 && <span className={cn("text-xs px-1.5 py-0.5 rounded-full ml-1 bg-black/20")}>{tab.count}</span>}
                        </button>
                    ))}
                </div>
            </div>

            {/* Content List */}
            <div className="flex-1 overflow-y-auto p-4 space-y-2">
                {/* Search & Add Toolbar */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-4">
                    {/* Search */}
                    <div className="relative group">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-text-muted group-focus-within:text-white transition-colors" />
                        <input
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            placeholder={`Search ${activeTab}...`}
                            className="w-full bg-black/20 border border-border/50 rounded-xl pl-10 pr-4 py-2.5 text-sm text-white placeholder:text-text-muted/50 focus:border-primary/50 focus:bg-black/40 outline-none transition-all"
                        />
                    </div>

                    {/* Add New */}
                    {activeTab !== 'online' && activeTab !== 'banned-ips' && (
                        <div className="flex gap-2">
                            <input
                                value={newPlayer}
                                onChange={(e) => setNewPlayer(e.target.value)}
                                onKeyDown={(e) => e.key === 'Enter' && handleAddPlayer()}
                                placeholder={`Add to ${activeTab}...`}
                                className="flex-1 bg-surface border border-border rounded-xl px-4 py-2.5 text-sm text-white placeholder:text-text-muted/50 focus:border-primary outline-none transition-all"
                                list="history-list"
                            />
                            <datalist id="history-list">
                                {playerHistory.map(p => <option key={p} value={p} />)}
                            </datalist>
                            <button
                                onClick={handleAddPlayer}
                                disabled={!newPlayer}
                                className="px-5 py-2.5 bg-primary text-black font-bold rounded-xl text-sm disabled:opacity-50 hover:bg-primary/90 transition-all flex items-center gap-2 shadow-lg shadow-primary/10"
                            >
                                <span className="hidden md:inline">Add</span>
                                <ArrowLeft className="w-4 h-4 rotate-180 md:hidden" />
                            </button>
                        </div>
                    )}
                </div>

                {/* Empty State */}
                {displayedList.length === 0 ? (
                    <div className="flex flex-col items-center justify-center h-64 text-text-muted animate-in fade-in zoom-in-95 duration-300">
                        <div className="w-16 h-16 rounded-full bg-surface/50 border border-border flex items-center justify-center mb-4">
                            {activeTab === 'online' && <Activity className="w-8 h-8 opacity-50" />}
                            {activeTab === 'ops' && <Crown className="w-8 h-8 opacity-50" />}
                            {activeTab === 'whitelist' && <UserCheck className="w-8 h-8 opacity-50" />}
                            {activeTab === 'banned' && <Ban className="w-8 h-8 opacity-50" />}
                            {activeTab === 'banned-ips' && <Ban className="w-8 h-8 opacity-50" />}
                        </div>
                        <h3 className="font-bold text-white mb-1">
                            {searchQuery ? 'No results match' : `No ${activeTab} players`}
                        </h3>
                        <p className="text-sm opacity-60">
                            {searchQuery ? 'Try a different search term' : 'The list is empty right now'}
                        </p>
                    </div>
                ) : (
                    <div className="space-y-2">
                        {displayedList.map((item, i) => {
                            const isOnline = activePlayers.includes(item.name);
                            return (
                                <div
                                    key={i}
                                    onClick={() => !item.isIp && setSelectedPlayer(item.name)}
                                    className={cn(
                                        "group bg-[#161b22] hover:bg-surface border border-border/30 hover:border-primary/30 rounded-xl p-3 flex items-center justify-between cursor-pointer transition-all hover:scale-[1.01] hover:shadow-md",
                                        item.isIp && "cursor-default hover:scale-100"
                                    )}
                                >
                                    <div className="flex items-center gap-4">
                                        {!item.isIp ? (
                                            <div className="relative">
                                                <div className="w-12 h-12 rounded-xl bg-black/20 border border-border/50 overflow-hidden">
                                                    <img
                                                        src={`https://minotar.net/avatar/${item.name}/48.png`}
                                                        className="w-full h-full object-cover transition-transform group-hover:scale-110"
                                                        onError={(e) => { (e.target as HTMLImageElement).src = ''; }}
                                                    />
                                                </div>
                                                {isOnline && (
                                                    <div className="absolute -bottom-1 -right-1 w-3.5 h-3.5 bg-green-500 border-2 border-[#161b22] rounded-full animate-pulse" />
                                                )}
                                            </div>
                                        ) : (
                                            <div className="w-12 h-12 rounded-xl bg-red-500/10 border border-red-500/20 flex items-center justify-center text-red-500">
                                                <Ban className="w-6 h-6" />
                                            </div>
                                        )}

                                        <div>
                                            <div className="flex items-center gap-2">
                                                <span className="font-bold text-white text-lg">{item.name}</span>
                                                {ops.some(o => o.name === item.name) && <Crown className="w-3.5 h-3.5 text-yellow-500 fill-yellow-500" />}
                                                {bannedPlayers.some(b => b.name === item.name) && <Ban className="w-3.5 h-3.5 text-red-500" />}
                                            </div>
                                            <div className="flex items-center gap-3 text-xs text-text-muted mt-0.5">
                                                {item.uuid && <span className="font-mono opacity-50">{item.uuid.substring(0, 8)}...</span>}
                                                {item.addedAt && <span>Added: {item.addedAt.split(' ')?.[0]}</span>}
                                                {activeTab === 'online' && <span className="text-green-400 font-bold">• Online Now</span>}
                                            </div>
                                        </div>
                                    </div>

                                    {item.isIp ? (
                                        <button
                                            onClick={(e) => { e.stopPropagation(); cmd(`pardon-ip ${item.name}`); }}
                                            className="px-3 py-1.5 rounded-lg bg-red-500/10 text-red-400 hover:bg-red-500/20 text-xs font-bold transition-colors border border-red-500/20"
                                        >
                                            Unban IP
                                        </button>
                                    ) : (
                                        <div className="flex items-center gap-4">
                                            <ArrowLeft className="w-5 h-5 text-text-muted opacity-0 group-hover:opacity-100 rotate-180 transition-all -translate-x-4 group-hover:translate-x-0" />
                                        </div>
                                    )}
                                </div>
                            );
                        })}
                    </div>
                )}
            </div>
        </div>
    );
}
